name: Deploy to Cloud Run

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - '.gitignore'
      - '.gcloudignore'

env:
  PROJECT_ID: project-ef671036-8080-43e8-bd9
  SERVICE_NAME: udrive-site
  REGION: us-central1

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/833430646448/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions-provider'
          service_account: 'github-actions-deploy@project-ef671036-8080-43e8-bd9.iam.gserviceaccount.com'

      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.SERVICE_NAME }}
          region: ${{ env.REGION }}
          source: ./
          project_id: ${{ env.PROJECT_ID }}
          flags: '--allow-unauthenticated'

      - name: Show Output
        run: echo ${{ steps.deploy.outputs.url }}
